spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socks?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  cache:
    multi:
      caffeine:
        expireAfterAccess: 5000
      redis:
        defaultExpiration: 60000
    cache-names: userIdCache,userNameCache

  redis:
    timeout: 10000
    password: ZU$K@Gbj^!gas3P8a
    host: r-bp17qyb797ymlnewcupd.redis.rds.aliyuncs.com
    port: 1438
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        min-idle: 0

# 阿里云 OpenSearch
open-search:
  app-name: xueshun
  access-key: LTAI5tFumu1ksg7tptATpBNC
  secret: jXkjrgSQyFcNqkVbid6TP2k4LW2xCN
  host: http://opensearch-cn-hangzhou.aliyuncs.com