spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socks?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  cache:
    multi:
      caffeine:
        expireAfterAccess: 5000
      redis:
        defaultExpiration: 60000
    cache-names: userIdCache,userNameCache

  redis:
    timeout: 10000
    password:
    host:
    port: 1438
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        min-idle: 0

# 阿里云 OpenSearch
open-search:
  app-name:
  access-key:
  secret:
  host: http://opensearch-cn-hangzhou.aliyuncs.com